---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  media-nfs-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 116Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: media-nfs-pvc # name of pvc which can claim this PV
    namespace: media # namespace for the pvc
  storageClassName: nfs
  volumeMode: Filesystem
