---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 116Ti
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Empty string for static provisioning
  volumeMode: Filesystem
  nfs:
    server: nfs.kube-system.svc.cluster.local
    path: /
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: media-nfs-pvc
    namespace: media
