apiVersion: v1
kind: Pod
metadata:
  name: barman-debug
  namespace: cnpg-system
  labels:
    app: barman-debug
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: debug
      image: public.ecr.aws/docker/library/debian:bookworm-slim
      command: ["sleep", "3600"]
      env:
        - name: AWS_ACCESS_KEY_ID
          value: "003410a18b211d00000000001"
        - name: AWS_SECRET_ACCESS_KEY
          value: "K003BAWC5NH36hqTFvk4NqeWYGkGiJ8"
        - name: AWS_DEFAULT_REGION
          value: "eu-central-003"
        - name: AWS_EC2_METADATA_DISABLED
          value: "true"
  restartPolicy: Never
