---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: affine
  namespace: flux-system
spec:
  interval: 1h
  url: oci://registry-1.docker.io/shrinedogg
  ref:
    tag: "0.1.1"