---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: agentgateway-crds
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/agentgateway/charts/agentgateway-crds
  ref:
    tag: "0.0.0-alpha.a655af15"
