apiVersion: v1
kind: Pod
metadata:
  name: network-test
  namespace: auth
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: tester
    image: nicolaka/netshoot:latest
    command: ["sh", "-c", "echo waiting && sleep 300"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
  restartPolicy: Never
