apiVersion: v1
kind: Pod
metadata:
  name: oidc-test
  namespace: auth
  labels:
    app.kubernetes.io/name: oauth2-proxy
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: tester
    image: nicolaka/netshoot:latest
    command: ["sh", "-c", "echo waiting && sleep 300"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
  restartPolicy: Never
