---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: continuwuity
  namespace: matrix
spec:
  hostnames:
    - matrix.biggs.dog
  parentRefs:
    - name: wildcard-biggs-dog
      namespace: networking
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /_matrix
      backendRefs:
        - name: continuwuity-service
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /_continuwuity/
      backendRefs:
        - name: continuwuity-service
          port: 8080
