apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nsyncd-secret
  namespace: nsyncd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: nsyncd-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        id_rsa: "{{ .sshKey }}"
        REMOTE_HOST: "{{ .remoteHost }}"
  data:
    - secretKey: sshKey
      remoteRef:
        key: biggkey
        property: biggkey
    - secretKey: remoteHost
      remoteRef:
        key: gregbob-ip
        property: ip
