---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app minimax-mcp
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
    - name: external-secrets
  targetNamespace: ai-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/cluster0/kubernetes/apps/ai-system/minimax-mcp/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 3m
  retryInterval: 1m
  timeout: 5m
