---
apiVersion: v1
kind: Namespace
metadata:
  name: renovate
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
  # labels:
  #   kustomize.toolkit.fluxcd.io/prune: disabled
