---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./nv-gpu-operator/ks.yaml
  - ./nvidia-gpu-tuning/ks.yaml
  - ./fenrir/ks.yaml
  - ./gpu-arbiter-operator/ks.yaml
  - ./gpu-arbiter-instance/ks.yaml
