---
apiVersion: v1
kind: Service
metadata:
  name: flux-operator-mcp
  namespace: flux-system
  labels:
    app.kubernetes.io/name: flux-operator-mcp
spec:
  selector:
    app.kubernetes.io/name: flux-operator-mcp
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: http
