apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: bookboss-user-password
spec:
  externalSecretName: bookboss-user-password
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: cnpg-system
  - matchLabels:
      kubernetes.io/metadata.name: media
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword-connect
    target:
      creationPolicy: Owner
    data:
    - secretKey: password
      remoteRef:
        key: "bookboss-user-password"
        property: password
    - secretKey: username
      remoteRef:
        key: "bookboss-user-password"
        property: username
