---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: object-store-secret
  namespace: cnpg-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
  - secretKey: ACCESS_KEY_ID
    remoteRef:
      key: "b2-object-store-keys"
      property: keyID
  - secretKey: SECRET_ACCESS_KEY
    remoteRef:
      key: "b2-object-store-keys"
      property: applicationKey

