apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jitsi
  namespace: jitsi
spec:
  interval: 3m
  chart:
    spec:
      chart: jitsi-meet
      version: 2.15.0
      sourceRef:
        kind: HelmRepository
        name: jitsi
        namespace: flux-system
  values:
    publicURL: "https://jitsi.biggs.dog"
    turnHost: "turn.biggs.dog"
    tz: Europe/Helsinki
    service:
      type: ClusterIP
      port: 80
    websockets:
      colibri:
        enabled: true
      xmpp:
        enabled: true
    enableAuth: true
    enableGuests: false
    web:
      image:
        repository: ghcr.io/jitsi-contrib/hardened-images/web
      service:
        type: ClusterIP
        port: 8000
      livenessProbe:
        httpGet:
          path: /
          port: 8000
      readinessProbe:
        httpGet:
          path: /
          port: 8000
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
      extraVolumes:
        - name: run
          emptyDir:
            sizeLimit: 32Mi
        - name: tmp
          emptyDir:
            sizeLimit: 32Mi
      extraVolumeMounts:
        - name: run
          mountPath: /run
        - name: tmp
          mountPath: /tmp
      ingress:
        enabled: false
    prosody:
      image:
        repository: ghcr.io/jitsi-contrib/hardened-images/prosody
      extraEnvFrom:
        - secretRef:
            name: jitsi-users
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
      extraVolumes:
        - name: run
          emptyDir:
            sizeLimit: 32Mi
        - name: tmp
          emptyDir:
            sizeLimit: 32Mi
        - name: prosody-lib
          emptyDir:
            sizeLimit: 16Mi
        - name: extra-config
          configMap:
            name: prosody-register-configmap
            defaultMode: 0755
      extraVolumeMounts:
        - name: run
          mountPath: /run
        - name: tmp
          mountPath: /tmp
        - name: prosody-lib
          mountPath: /var/lib/prosody
        - name: extra-config
          mountPath: /etc/cont-init.d/15-disable-tls
          subPath: 15-disable-tls
        - name: extra-config
          mountPath: /etc/s6-overlay/scripts/register-custom-users
          subPath: 75-register-custom-users
        - name: extra-config
          mountPath: /etc/s6-overlay/s6-rc.d/75-register-custom-users/type
          subPath: oneshot-type
        - name: extra-config
          mountPath: /etc/s6-overlay/s6-rc.d/75-register-custom-users/up
          subPath: oneshot-up
        - name: extra-config
          mountPath: /etc/s6-overlay/s6-rc.d/75-register-custom-users/dependencies.d/70-register-setup
          subPath: empty
        - name: extra-config
          mountPath: /etc/s6-overlay/s6-rc.d/user/contents.d/75-register-custom-users
          subPath: empty
      persistence:
        enabled: true
        size: 3Gi
        storageClassName: ceph-block
    jicofo:
      image:
        repository: ghcr.io/jitsi-contrib/hardened-images/jicofo
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
      extraVolumes:
        - name: run
          emptyDir:
            sizeLimit: 32Mi
        - name: tmp
          emptyDir:
            sizeLimit: 32Mi
      extraVolumeMounts:
        - name: run
          mountPath: /run
        - name: tmp
          mountPath: /tmp
    jvb:
      image:
        repository: ghcr.io/jitsi-contrib/hardened-images/jvb
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
      extraVolumes:
        - name: run
          emptyDir:
            sizeLimit: 32Mi
        - name: tmp
          emptyDir:
            sizeLimit: 32Mi
      extraVolumeMounts:
        - name: run
          mountPath: /run
        - name: tmp
          mountPath: /tmp
      service:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "192.168.2.9"
      useInternalStun: true
      publicIPs:
        - 192.168.2.9
    coturn:
      enabled: true
      replicaCount: 1
      image:
        repository: coturn/coturn
        tag: "4.9"
      turns:
        enabled: true
        certificate:
          create: true
          issuerRef:
            name: letsencrypt-prod
            kind: ClusterIssuer
            group: cert-manager.io
      service:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "192.168.2.10"
      allowedPeerIPs:
        - "10.244.0.0-10.244.255.255"
      extraVolumes:
        - name: run
          emptyDir:
            sizeLimit: 32Mi
      extraVolumeMounts:
        - name: run
          mountPath: /var/run
