apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: jvb-user-password
    namespace: jitsi
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword-connect
    target:
        creationPolicy: Owner
    data:
        - secretKey: JIBRI_XMPP_PASSWORD
          remoteRef:
            key: jvb-admin-credentials
            property: password
        - secretKey: JIBRI_XMPP_USERNAME
          remoteRef:
            key: jvb-admin-credentials
            property: username

