apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Foundation
  - apps/cert-manager/kustomization.yaml
  - apps/external-secrets/kustomization.yaml
  # Networking
  - apps/networking/kustomization.yaml
  # Apps
  - apps/auth/kustomization.yaml
  - apps/omni/kustomization.yaml
  - apps/netbird/kustomization.yaml
