apiVersion: v1
kind: Service
metadata:
  name: omni-ui
  namespace: omni
  labels:
    app.kubernetes.io/name: omni
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: omni
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
