apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs
  name: nfs
  namespace: media
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nfs
  template:
    metadata:
      labels:
        app: nfs
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: quay.io/aminvakil/alpine-nfs-server:latest
          imagePullPolicy: Always
          name: nfs-server
          env:
            - name: NFS_THREADS
              value: "32"
            - name: SHARED_DIRECTORY
              value: "nfs-share"
          ports:
            - name: nfs-port
              containerPort: 2049
              protocol: TCP
          volumeMounts:
            - name: media
              mountPath: /nfs-share
          securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            privileged: true
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "echo \"Stopping NFS server gracefully...\"; exportfs -uav; sleep 5"]
          resources:
            requests:
              memory: 12Mi
              cpu: 25m
            limits:
              memory: 12Mi
              cpu: 25m
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: "media-zfs-pvc"
