---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cert-manager-csi-driver
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/cluster1/kubernetes/apps/ai-system/csi-driver
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 3m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cert-manager
