apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: flux-operator
      version: 0.52.0
      sourceRef:
        kind: OCIRepository
        name: flux-operator
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    networkPolicy:
      ingress:
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: flux-system
