apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:zX1ZSInaS7x5rU1zSfRv854W4qQbfLb5ND8BiyEW4XaS8e2ABv1p8UYkuOleZzpyyVZkO7B/85lD3JciLLXnDwDygOmlw651hVmUXax7XsuujBQxk/+sJQOzZYNo5trpxlaQdYRNprzRHWLbUkIvrnrBi6W1gi40yYDAL1ZtF+iE+A5wLOP+fcmlfpBB6mc0yAmk4we7hH9zCnYqauIMYaI5ehUgrLpMAQzaRY7R2mSIjyaQmpd1eD0rTKOH/PHn0+xeADiUdfgyIgHD5xJQs1L7FzTQ/uflSy2DeKn6s9aPma8r7en/on1PFqAF5zd2T8kzSlVI5FJ+jfL4wnAWtI/DmEzGR3FOvMRT3oQ71S6COOV2DN+RwknS+6cVBZ1fWnHuDewP8q9wEtyFK0QclF6aXifZo0N0dwsUfdLstfIeRFF/PGrd33URWAWB+d7TYkJBEJp/ZJuzWShWriEKHozcKcuQgM0Rim3DigosFWKkOd15kbkeI0nrdW6XbybW2RWZn+xTDM06zHcUO9NKlzObwRZV0NIzFq3U88RqdtoDIBX6y56co6lVoYlpJzSjhUuVXZDN+eRLo6sJdRptvz6iztIfFJYFXyzJHea8VGDcKzaGXdDS4SJwOmJ4g06luxQnQ0Eec6UcnZX9v9sgpUeK181jufuPL3dupQo2TjFu648tZ+EvrIX6FqP6FKjzT3LrlTfnGUP4szsHeL7oR8OdpXaPmfAEmZZJmKdCWmuwvRED+iIEJVrqIjYoJ9thu1/0hL4RFcqtzuZwrd4+JmfnsxRqLU6WaqNlD8zZkxhalDtpBj9kUApXL4QMm4MYgUaPW+c0c71KnD4QCGg8lJ40W1l6N9PR7+eveigYe9SK3Ulwd38fHhWCizSYCTD+5mfvSzdx0o5CWYrMK8YKCKtgGsjoZvQaAftk+Shc34Km+SLnLefW+8U2yrjuciPZsEANmjhPzUMUStVXNt7uazA9Et5iP8gjEibS0e6OT3BIZTri73Hb7V8rizPAcxxmOsyeWBbz+OhEdMTHDI2h7owa/E+NOc5jZrZno+IlTjrRpq8UbbYROXf2Du+UxA10LLBP1t/jjghbj70VX0T9Rd4LfIQ0qwZV8aDRD5RU6ugYHCoVOy8urMOw+72+bUyRdV/zV6AHJa5cwALDo6NhQCivEl0KG3iDhX5cXZVs59dbc0Xd5Bc9A5fLAypE+mTM7ElHqkSiDzrH7P/ufehkugzlVVsvpS4eXUzh267bL6eUOSlIYN5k19LVPqllxiQYfBnDPjndpT39XDUmxdpOh67RIAyBqIYhFhwFagrPPhtm+ThfL6tywXWqL4LCfj/5c/YRVe+0KQzrgLNAxWgNf/DgXyQyiWE5rYzkKP0wktoPHOWw8QoxE9lAAn67Lbi43hY2SSlyxo/Ci+nfxpC684Om4+4zWwehfA4rGTsKEbtXXcgOOhmWDY1qO+sTHefnyzZA+2PTdUM2PszDsbeN4ujvcX/Qcrqt/bKpVoGFumjr2/4lvAL5F+Jx/1MWPtTHiHjZyhOfaNZ11GCBheXygkQuOkGr7ZpVYxAkEz+VFcQPh0UA9JOCY1LYIkvHaUjOMX2jAF2US0uF3/f8ZPVIYlLlQtYneOoRFEmeceK9L10iJCV8/m300ezPC2CI3XSUz2G4BWz1wU721MoNFlkcD24Ro8jVVCpUmX3HW2ps2sFOUKpoDDVYcoQxJxUkOVYWDsEboWLjV9Rc1qZuewBVX7YF/WRMTpOEt4di8YTq6ET0Hqgx9fGtyYgFXeM3t0CxI/HrdwOYFHLadslw+HpWih1J+zkfk6BGbBqG3uz2sugacVL4Xcw/HH60ARRsqefrPh4D7qScbhWJ9grofmwKp0BnuXMF0NCt9coCzeIUbUGsCo51Ucd9rkb8iATiolpdWAyfxE36eDhPcojZ,iv:3hR2031VvpkmSQ7+6aCp0/G5ufUkaf4YrKRwryC6VeM=,tag:eOThzUYQ/Zio25KXAP9ZQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age190ldxpeqm783nz8rf3cxeajq2m0rflan4huhau8fz9tqcj96wgvsmycw9d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQjYzWWJwVE9tZURJbWNq
            Mm9teGtJdnc5Slp4Z3JSVUwrd0d4czFSZlRvCnlMc2FMVjFzeUtiQ3l5WDFvaW9Z
            TVdoSUVJYnZCdnF5V0V4VEUydWtzT0UKLS0tIGdSYXBZM0lWUmdHS1J4ZDNaVW1C
            Mk40b2hzODlGd3RyRElsODUxUUJTN1EKpq0IbYSYoZhBJ8SGF0k2ZgwbA3S4Mmls
            O19dkCg5kHRCaiZffSYQex2Mug/tUUpShWc/t0Npm3E68vLZb3er7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T12:55:15Z"
    mac: ENC[AES256_GCM,data:4h4kX/2136XkyugFDzMldWCv92+S4sMOz7QI+hRdgA1TJimUuMsshMLwjffjcLZBWurmJqk7S6ED34OmHwFMobi6GMTYxnq5IYn5xwqDcuLePMC+P9CIjuaMI222TJNIV6QkgjLKFQ/AxqRimRpCxMBVWF4oDz+HYLKTbj5Px88=,iv:i8l+x90D/TR6ZniuVxTnYgtihHSmyco+PaT/lt/dfr4=,tag:HsKwZI4ttJv5TxCe40aVUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
