apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:KhFE1e8gZBGd3IVVAWnHd8rYq1Mal6Jj5ogyCYqDmlB3vHc4VwMNfyWK/RRdjuFRmZqiJozSYAp7nvuUy9ZpzFXwaKMQ3zp1IL3xjCuy1nFVbTWKQ88a/vsOmK9o27JWWzlmlk6ZxviVG1/2T5G3psXQ48jiiEU1Cv1yzgxJbc8TI0lurFVM/wxFfFjcW20dUWB6+s9uSQAPV2iHCG9EajWqs1892AF0p76K90zCxA7LT4Bg8B3xv2aFlGdrQRd0aABTXj+TM49dGq8SghVTeYoWwT6lugEfERiwalMnTzgZCerI5ddC0nd6iNX6BhKCSRdkVxjfMBOotMstACh246aizdPwo/gSbZyRTXKXJH17DrdhCNUhQ5SvN1tqHGi75JOVlTA0nEjq9Q1UG9Fz6fY5B/QNN0QtFRfsrbDHeEmbRc9m0hfR0SkUgP3vSLSCKRXaJTPCbc7KXslUykx5nIo9ni6CZQP9MxKP8hD5LR3NgpLkr8RFk8R0IlQDunQgFjuAVin7fp0LsMFhlIBoiVVO8H57JOedVMSv5bvDKxZvxM/cqSzQMEnrrvJxtREfH7tsRwNOVWlsdBx9XYTx8X7+E/XT4cA0iojYvowsmL/MgqI0uuUlvUTg0QUJh7Zene2mbhHiTUgDat8q/g7E6z1qSk3oGQHtz7X+GXhlDuEa1hA4CrZTyw4PkQ08zsISMvNud7J4kwBErwbmaE1Xp1g5XjlDmzFrwRNfgzT05/CCV/52iutLkY9AfR+F8nmAakAwml++XWprkmcGKF5VZHyZ8MLQlICeT+w2i36e7Gjp7OnIwBlspIH9bfpk+GS9P2XCS1yW6u/nGBgDZ1Kk,iv:D4I3oPqvGCc/UITwRtj/Z66H0SRErJtb7EWBvRp7KJY=,tag:dA9LxB8blNTqn4monSsV7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTkV6TUIyRW81U3FPbC8v
            KzEwRTc1N2huT2ZkRzJZOGFPZk9RdENOWUhBCjhrU09JTEJlcXNTK0hHTTQ2cDlF
            NHNwSHo1VVo0M2luNDlhdDBmRmZMQUEKLS0tIHY4NGZwVGhwaHU1alg2bFlqWm1Y
            SXhUN2dxT1FhajNYVEtKQk55aFoxSEkKooCQYJ0jWRP9lWE94KP8QJK19Uh7EZkF
            JaElgDxMSTBCn7kNRwbYSYozGzax0Fkmjg2zTaYdlUjTg3xi9vlCeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mlu0sfujfyh3w0hm94azdz6d88yu0jmvdy8t5hs7j8q6jtwm2ejsch03hg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxU2h4aGw5OG9CaEVHZ1No
            M3Z1VFdwOWRiS292Nk5UclFYUWNoNzVOdlZvClRWRm1mbWZBR3B2dWtGb0RJM3hK
            TTQ2THNSZ1J4aHlVRWpuQzI4Z1pjUEEKLS0tIENMVGs0TnlNSSszeUdKTTFQMkU0
            dTM2M09jcjhPYmc1cm81ektvNUt1UmcKMCBrTi3Eumx6rCo7inrNE0Qh/1LeCBrY
            5W+fvQJcsUUm1tEGxQ+h25GRJrtyDpVWozA7CrqkdgfDisEQn7YQWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tcr89ezp74jk9xmfzmra3k26644w38xmep7azhxgy968285jrvvska5j8k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T14:55:16Z"
    mac: ENC[AES256_GCM,data:c05zMaaUW0vnzJ3tjDif89qh7E9rdRKMSjZ+sSjiuarTecYLTEpC1MHb9HjtEci2+JQfjhOsOvtbPl/i923UYzqEjSV0Fcyz/5ak0f+8WYSTMxnw3lniRqSyJG1E1DTkRZQzjNZRKg7EDFwzMOKVK5Ykjvvxi4HApJ81JaKxfU8=,iv:me3bs6Be6W5xBDrHoP+yZmgjcAP9hWvd/vdzzLe6S7Q=,tag:/ehxpMAQwBdVQsm8+R1DBA==,type:str]
    version: 3.13.2
