apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:Kj9G3EMWBLrm0CUfaJ2XxjLYYkzW9uwI1WDlDba+S6WAJVtADzgOAVIv/Am6GSoxghQjqlH72NUeYCr65fh8udMxpE7zisS8b8Cc3FoyqcWQxjLImDRK4P/afbh2CF7QyXlu6f32B4SfhCb8mz2xHzuSrWe/NFhQqb4PibH9oLCuP7pSKKMns5+MFJyyLWLSK2x42Rh+B1aYWxiqiszvj/0UJODyh2ayZp1Lsvtu8AF/lNZLQgXBXidu80uHSaRu2XkOZ1p6gDwXvq18SaOzQVBqIF1lAp6QW2ytlOCN+nc575LzAHG61UV+5poakxIjUpKshAM8dpr04VlVdtVmpTk/JOBv1k01FKV3WSjJaRiMSy22dSfMMy2sI5aT8+/vGMYde958AsE3QyH/BKKx48MzAefZjBoOaIciDHiqk9OvXraNbNN/+WWfG03UU70OmwYPMCtokdThPz12c+eBoOqAjEMwqGhTlqCvsyBOzfeMHR6JRYuUuOr1Cp+OXSsYgMbnEmfReZQ/7b5mv/QSVcQlYm0BH0wy9FehIAjoTNwX7ARxG17sRCMpPSLCxzfOo/3IKcOjmLBEzmXn+sH/Zckhek7rE3D0UZKsMo4XBi8scWSRwb59RK/Q/5cZQnF5o0xZT5g93SOHoyzJKvCmHTmt7/YxyEbirFhTJopWxcF8oa/0HC+Y/8AayivBXuJwDdzo3A5oL+Ho91wE/uITiLDYm25MiNS2jxmWfEq74glGf0QsNK8S8ErOcWsXuboUAWfChOmgDrA5LRvz7BOVbq7ZwbSNftLoCF+6Io29LAs+grxhsl18a7iyGQOgSpmnjqaGP5K203RT36Hy4YOzHnEwnE9DWtEIu5PnAQZFkZyYy6Fobgsa9ena/MtrRqjPfvt+DGFzD/VS06G2fm90DPsyYNGEuCCgmtA5Zbco+iKiR0rM6D4TKt0X/ImP5Xd3yfkd1ZqNgrBD/H+B7MhsgDZmk/twCoEQvxs2tVafr94LUmYoc1p4ydNJ4ayD61qI4GowOhoT8oaBvUow8gb2m1WAXCYbSv9g+dDEeIzpOVoBHG3sJKl7TVsYhnbNxI/MNNQQgMtHGwB9smayEika196R+7Auh2Pm4tf14SmXgUVPZSgGe6jNG0sbOaRuzkvjkg3t6QQ5omxW+4/FMvW5FOkMsqA5oDzRpL9wDfuM+29MX/x6VcOC7ZZth9TNl5UMgNPVcBYEgJbL4br+DHfdgQSCpEvevfmkFZ6At+vmSXBlO5D/a+DPkS69J6rhiUPTcd2GwnUJyHlJotqpM6wHLsGiGsFLai+LqxWT0NyKqSflc220mVi37zEnp8dQj5TgHg9wfv9UfzRIwAzK+Hjp2/uNCA8dAf63xaNvGlEinpPSivxkvlVqsUiZynJMaNtfNmjbP0LTq+swsheMhzFRriZGjQJsj/u71qvHsBOSyA==,iv:68arCOXgyZMa26Z/orqovZytrUvAOggfNYSMGhegOSw=,tag:XF0DYdYE/p3AQfpzZIh8zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age190ldxpeqm783nz8rf3cxeajq2m0rflan4huhau8fz9tqcj96wgvsmycw9d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydElKWmFiellIUkhnbmxi
            aHh1dG5lT3VDdEVWZWhEZjFYamZGNmkrdGxJCkJnWEM2MXpta2lmK1A5eTNET004
            M29ib2FFbkNJVnhRQTlYT0NpQ04vTkUKLS0tIG1Jd1NZWEVCTjd0Wi91R1AycHU3
            UytkTjUwcTkvTXVSVzdISkFVMXFtU2cKmWgUcZWd8oE8Lcc1gB85XSNEdhLxx8l8
            GXvSBnqGnUseGepVoLryCGUe5yyt1Rhn4hKSaiWKFzQ5jekUSTmV1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T13:12:00Z"
    mac: ENC[AES256_GCM,data:5+KrosStOTU3+iSg95s6C2GLzNvw26jRbMSR9raulA1cCZF9t0ZDbl3DuBg8NYKQHIsvAGowqPhFsebgEad6tK5JKFEfUQs7rHq6IdffszTBXGXoouJikdcb5DGMWJBkmLDGx69ovxxsGo9Qjui1PkxkbdqG7pEq26u5nd3DZZo=,iv:bNm+Cib2/1nQVCP+LVZBfgOnmUFkr58QtF/2oHZksEA=,tag:p3pM82DLf/yINzRx2topAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
