apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:gUpvZyplW/2/Q/sMTiKFIH6TJWdYwSzp1ex9Zf6lP7A0Ym/dyFl7jWuWfTioY6OMwoxhHclap+Amcga0KVY/P8z4OspwXTgqp6wb9+gtZa/XX9DEZksQ5ck92evcRNI+cBakojh4fKEMnEVfgPUX6ilyd6/xg100ncq8rQhekIXwRvGwpCxpzSGRNeubuDOVbL8YYiv7SKNjdc9/MbZFwYj78y0ICLweqnd/TFLgJsUhYcIU5rT3WfodOh3tLfMoS3ogSkdRr8k23Egm0iPDBw3bbT26qC9pLPcbsSZOhDh8aWiyqPP2dhA9OEcp8ObV8ffMTQxEePjAce6zPUIahhXh2zO0KVFUjif3cUfuDWl5b8xEqLNShqatjlaKYZGOwcY5jQvYsxZtAuB0ZDtQy04GtYR4KQ6UhIODSg6/fJLogh2e3DG9sAh8FIpzz6Vr+zL4LRo+RL1I6iTwQ0lvMWu3l8MxkeTceiHEthu6OxerIxQRM/tjowZohVDfms6SLEblBbf4aHKiSjkUtiUK43PlYIc7HzLLeetKTay0eVWtQarpuDACAsS7Jo5Tarolm+gpePp4dUu0HBv/bGyP0E2TkMDfj0glFVMblpRQft2yVPyvSVtCDY425Iu/QQtFxqRzzjHZrPiw8KSduSldPXlrtEjMQTboUag/vlI92yG2J2FBDSQknTCPpIFCra8ct2DPG4u9zT6Y4eJ5y+FVs46xj1FsotrEMwu5HMbVVJUUqomfN/hzpQeHYhU3lfXpIxC7+5fpK3HXw5tkY6H8KxW98Jhjsrpt/IRy5pWm1P1KWm1I3X7Y7zEcqCsl0CXuxSnc8eGrMNtVmrlWiT5RLw1a71l1byXi2MeUPFxX/34SFVLjXDzhWlP5utlEBx2UK/IWHMLvfJDVfmST8qt1cvtoyvMvjPJt5hUvAlfXxqGP7tudXzdsS8IvNbrJ6wB+1fj+Q3H9R69bKaKgH6e6h1zizLPmRCjee7uLRdbrsHSgHGs2Qbef7ERxnIskSNTIvBTyZEMeebncah9aNlK9/bOEY7vFXHRmbz1xrLNEmeRzArI7MpVKowMfFtNUa9S4B093VO+Uxn/OTY3TxdvqUzzKFSRhojiDvFPWovDslN8Z6oC/3OHR+1oM3mmXXNwRJOV5pDlZar87q60u5SMb1S72E6Z45QI/Ppj+yi4u4fF7IdK8tsKpRj7PyqB2U0FPx00xdCYCT5wP9rBRN6XknMn1NLU+BcwW/8r4PwJ4WMtLhZ45+CI1TEz0EtgW5VoIctKUHQBh7z+fMnm2toYTksUxWREFBEFqf8PveS9HcuyphB/xLtrjFgnzgVIQDgOzGOlIyBwNaO1m5uBlanHbLo/FH5ETxxkECVa5rmGWr/QNSLCOPEj3PppjaOF1eAHE0Hqe7sFc25mSiHZeVB78sM482yaJy99YerSE8Tphnw==,iv:avva5LQTIiV741JNWK4zK4yjHiKc69bqFrwLJZkDP88=,tag:TDJiT3zalPVFWStSJb84+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtL0NqbGhJS05QdVBvMFN1
            OFRRZVpQVU02Tkp1cGhaMDZZWlMwZGdvZmlBCjdISDFpRmtxRW14TzFibVpKWG54
            a1JhbEVHY3haRE1JeWVuMjhuaXNDSUUKLS0tIDlCb0hPR1ZIOUNVNEtxYVZ2UDJp
            L241ckdHeG5vTVd4c1k1cEQ1VnIxMVEKJ/E10qTKeGiZuUva8nzAFFxEd3YbGipS
            nRVwM39FOfcfvv9zDyfffrGhOB2lFPmfnGIoc+O7QAY/7puHVucSxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mlu0sfujfyh3w0hm94azdz6d88yu0jmvdy8t5hs7j8q6jtwm2ejsch03hg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMHlXZzNQc0JhZ0gvWXRh
            cXhoMjRYVUtFRkRxRWJQWDlUcWdtMDlOVEVZCjBLcy9YS01QMlBCdGlpcCtHamla
            cVQrNjMxY3hCK2M5Vm9hcG1DZUJlaDgKLS0tIDMvTWdEMEZKRjI4TVNINUFpQUtC
            eDVZeVBGMTM0SFNMN1Z0Lzd5aytLb00KDHAwWs3meedWNA5vIm+p/IL8Q6itHNg2
            vwIISKmxEN/W5HPyQ3dmhpqfx+2afzNL77nLFWRuypxEddKC/1mg9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tcr89ezp74jk9xmfzmra3k26644w38xmep7azhxgy968285jrvvska5j8k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T14:47:19Z"
    mac: ENC[AES256_GCM,data:w1ta7n8p5tiVWe2538Jvc7kei/MFAB/nbuuGF6DdTOVuoot8IWKSxxpVBalff+dkxt8ewEeck6+J8YivpUvQjHsbjsgP0iqaqnHlvy3wTi5kMOTlPUm1P1OQtId14q7GQItFsndsMSJVm0KiOSGfeCQdVH64GUc7eJpq6SL9Q7c=,iv:bL9TE71uDXsWtxQM4lM7l1sc2p79VYlxM0FLma/FT/U=,tag:sm9feKEIMZIUszV+L8/exQ==,type:str]
    version: 3.13.2
