apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windrose-data-pvc
  namespace: games
  labels:
    app: windrose
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40G
  storageClassName: ceph-block
