apiVersion: v1
kind: Service
metadata:
  name: windrose-service
  namespace: games
spec:
  type: LoadBalancer
  selector:
    app: windrose
  ports:
    - name: windrose-tcp
      port: 7777
      protocol: TCP
      targetPort: 7777
    - name: windrose-udp
      port: 7777
      protocol: UDP
      targetPort: 7777
