---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: wildcard-biggs-dog
  namespace: networking
spec:
  gatewayClassName: agentgateway
  listeners:
  - hostname: "*.biggs.dog"
    name: wildcard-biggs-dog-http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - hostname: "*.biggs.dog"
    name: wildcard-biggs-dog-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: biggs-dog-tls