---
apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-config
  namespace: livekit
  labels:
    app.kubernetes.io/name: livekit
data:
  livekit.yaml: |
    port: 7880
    bind_addresses:
      - 0.0.0.0
    keys:
      {{ .env LIVEKIT_KEY }}: {{ .env LIVEKIT_SECRET }}
    rtc:
      tcp_port: 7881
      port_range_start: 50100
      port_range_end: 50200
      use_external_ip: true
      enable_loopback_candidate: false
