---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: livekit-credentials
  namespace: livekit
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: livekit-credentials
  data:
    - secretKey: LIVEKIT_KEY
      remoteRef:
        key: livekit-credentials
        property: key
    - secretKey: LIVEKIT_SECRET
      remoteRef:
        key: livekit-credentials
        property: secret
  template:
    engineVersions: v2
    data:
      keys: "{{ .LIVEKIT_KEY }}:{{ .LIVEKIT_SECRET }}"
