apiVersion: v1
kind: Service
metadata:
  name: omni-siderolink
  namespace: omni
  labels:
    app.kubernetes.io/name: omni
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: omni
  ports:
    - name: machine-api
      port: 8090
      targetPort: 8090
      protocol: TCP
    - name: event-sink
      port: 8091
      targetPort: 8091
      protocol: TCP
    - name: k8s-proxy
      port: 8100
      targetPort: 8100
      protocol: TCP
    - name: wireguard
      port: 50180
      targetPort: 50180
      protocol: UDP
