resources:
  - helmrelease.yaml
  - cilium-debug-agent-sandbox-agent.yaml
  - cilium-manager-agent-sandbox-agent.yaml
  - cilium-policy-agent-sandbox-agent.yaml
  - exa-agent-sandbox-agent.yaml
  - flux-agent-sandbox-agent.yaml
  - helm-agent-sandbox-agent.yaml
  - k8s-agent-sandbox-agent.yaml
  - observability-agent-sandbox-agent.yaml
  - promql-agent-sandbox-agent.yaml
  - vm-agent-sandbox-agent.yaml
