---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: continuwuity
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/continuwuity/continuwuity
  ref:
    tag: "v26.9.0"
    digest: sha256:5cc03961412fb74836a14599cda3bfa17f003df902d9555281fa973976c5243b