---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: continuwuity
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/continuwuity/continuwuity
  ref:
    tag: "v26.9.1"
    digest: sha256:c9c62bc5c0a641f3f713945c701b069c7bc30d2612b54d4a5de80a5be19d5420