---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: direwolf-operator
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/games-on-whales/charts/direwolf-operator
  ref:
    tag: "0.0.1-25011901255-SNAPSHOT"
