---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k8s-gateway
  namespace: flux-system
spec:
  interval: 1h
  url: oci://codeberg.org/k8s-gateway/charts/k8s-gateway
  ref:
    tag: "3.7.2"
