apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: barman-object-store
  namespace: cnpg-system
spec:
  instanceSidecarConfiguration:
    env:
    - name: AWS_REQUEST_CHECKSUM_CALCULATION
      value: when_required
    - name: AWS_RESPONSE_CHECKSUM_VALIDATION
      value: when_required
  configuration:
    destinationPath: s3://biggs-dog/
    endpointURL: https://s3.eu-central-003.backblazeb2.com
    s3Credentials:
      accessKeyId:
        name: object-store-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: object-store-secret
        key: SECRET_ACCESS_KEY
    wal:
      compression: bzip2
      maxParallel: 4
  retentionPolicy: 7d
