---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./vllm/ks.yaml
  - ./agent-sandbox/ks.yaml
  - ./kagent-crds/ks.yaml
  - ./kagent/ks.yaml
  - ./flux-mcp/ks.yaml
