---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./nfd/ks.yaml - disabled due to nv-gpu-operator installation nfd became redundant
  - ./nfs/ks.yaml
  - ./zfs/ks.yaml
  - ./intel-gpu-plugin/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./volsync/ks.yaml
  - ./cilium/ks.yaml
  - ./generic-device-plugin/ks.yaml
  - ./coredns/ks.yaml
