---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mindwtr
  namespace: flux-system
spec:
  dependsOn:
    - name: secretstore
    - name: agentgateway
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/cluster1/kubernetes/apps/mindwtr/mindwtr/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 3m
  retryInterval: 1m
  timeout: 2m
