apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ersatz-nfs-pvc
  namespace: media
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 116Ti