---
apiVersion: v1
kind: Service
metadata:
  name: livekit-service
  namespace: matrix
  labels:
    app.kubernetes.io/name: livekit
spec:
  selector:
    app.kubernetes.io/name: livekit
  clusterIP: None
  ports:
    - name: http
      port: 7880
      protocol: TCP
      targetPort: 7880
