apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-bookboss
  namespace: cnpg-system
spec:
  instances: 3
  bootstrap:
    initdb:
      database: bookboss
      owner: bookboss
      dataChecksums: true
      secret:
        name: bookboss-user-password
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1
  resources:
    requests:
      memory: 300Mi
      cpu: 150m
    limits:
      memory: 300Mi
      cpu: 150m
  storage:
    storageClass: host-path
    size: 5Gi
  postgresql:
    parameters:
      archive_mode: "off"
