apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-affine
  namespace: cnpg-system
spec:
  instances: 3
  bootstrap:
    initdb:
      database: affine
      owner: affine
      dataChecksums: true
      secret:
        name: affine-user-password
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1
  resources:
    requests:
      memory: 300Mi
      cpu:  150m
    limits:
      memory: 300Mi
      cpu: 150m
  storage:
    storageClass: host-path
    size: 5Gi
  postgresql:
    extensions:
    - name: pgvector
      image:
        reference: ghcr.io/cloudnative-pg/pgvector:0.8.2-18-trixie
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: barman-object-store
