port: 7880

redis:
  address: dragonfly.database.svc:6379
  db: 11

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: false
  enable_loopback_candidate: false

room:
  auto_create: false

turn:
  enabled: false

# prometheus:
#   port: 6789
# log_level: info

key_file: /config/keys.yaml