apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: livekit
  name: livekit
  namespace: matrix
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: livekit
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      containers:
        - name: livekit
          image: livekit/livekit-server:v1.9.11
          imagePullPolicy: Always
          env:
          - name: TZ
            value: "Europe/Helsinki"
          - name: LIVEKIT_CONFIG
            valueFrom:
              configMapKeyRef:
                name: livekit-configmap
                key: config.yaml
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
          - name: livekit-config
            mountPath: /config
          resources:
            requests:
              memory: "768Mi"
              cpu: "350m"
            limits:
              memory: "768Mi"
              cpu: "350m"
          ports:
          - name: livekit-http
            containerPort: 7880
            protocol: TCP
          - name: livekit-rtc-tcp
            containerPort: 7881
            protocol: TCP
          - name: livekit-turn-udp
            containerPort: 3478
            protocol: UDP
        - name: booklore
          image: ghcr.io/booklore-app/booklore:v1.18.5
          imagePullPolicy: Always
          env:
          - name: TZ
            value: "Europe/Helsinki"
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: BOOKLORE_PORT
            value: "6060"
          - name: DATABASE_URL
            value: "jdbc:mariadb://127.0.0.1:3306/booklore"
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: booklore-user-password
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: booklore-user-password
                key: password
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
          - name: booklore-port
            containerPort: 6060
            protocol: TCP
          volumeMounts:
          - name: booklore-data
            mountPath: /app/data
          - name: booklore-bookdrop-pvc
            mountPath: /bookdrop
          - name: books
            mountPath: /ebooks
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "2"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: mariadb-config
        persistentVolumeClaim:
          claimName: "booklore-mariadb-pvc"
      - name: booklore-data
        persistentVolumeClaim:
          claimName: "booklore-data-pvc"
      - name: booklore-bookdrop-pvc
        persistentVolumeClaim:
          claimName: "booklore-bookdrop-pvc"
      - name: books
        persistentVolumeClaim:
          claimName: media-nfs-pvc
  selector:
    matchLabels:
      app: booklore
---
          app:
            image:
              repository: livekit/livekit-server
              tag: v1.9.11@sha256:289262ffae8b827f45186331aa315d08ed275eb30f9b0add337ec57948e44ca1
            ports:
              - containerPort: 7880
                name: http
                protocol: TCP
              - containerPort: 7881
                hostPort: 7881
                name: rtc-tcp
                protocol: TCP
              #              - containerPort: 443
              #                hostPort: 443
              #                name: turn-tls
              #                protocol: TCP
              - containerPort: 3478
                hostPort: 3478
                name: turn-udp
                protocol: UDP
            env:
              LIVEKIT_CONFIG:
                valueFrom:
                  configMapKeyRef:
                    name: livekit-configmap
                    key: config.yaml
---
      jwt:
        containers:
          app:
            image:
              repository: ghcr.io/element-hq/lk-jwt-service
              tag: 0.4.1@sha256:6beec945a59b9b8b02161d29884abc2c1e5af9a376c1a2ccabbec3e26b07cf0c
            env:
              LIVEKIT_URL: wss://livekit.${SECRET_DOMAIN}
              LIVEKIT_KEY_FILE: /config/keys.yaml
              LIVEKIT_FULL_ACCESS_HOMESERVERS: "${SECRET_DOMAIN}"
            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true