apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netbird-secrets
  namespace: netbird
  labels:
    app.kubernetes.io/name: netbird
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: netbird-secrets
    creationPolicy: Owner
  data:
    - secretKey: encryption-key
      remoteRef:
        key: netbird-datastore-encryption-key
        property: password
    - secretKey: relay-secret
      remoteRef:
        key: netbird-relay-secret
        property: password
