apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: booklore
  name: booklore
  namespace: media
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: booklore
    spec:
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      containers:
        - name: mariadb
          image: lscr.io/linuxserver/mariadb:11.4.9
          imagePullPolicy: Always
          env:
          - name: TZ
            value: "Europe/Helsinki"
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: MYSQL_DATABASE
            value: "booklore"
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: booklore-user-password
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: booklore-user-password
                key: password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: booklore-user-password
                key: root-password
          securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
              add:
                - SETUID
                - SETGID
                - CHOWN
                - DAC_OVERRIDE
          volumeMounts:
          - name: mariadb-config
            mountPath: /config
          - name: mariadb-run
            mountPath: /run
          resources:
            requests:
              memory: "768Mi"
              cpu: "350m"
            limits:
              memory: "768Mi"
              cpu: "350m"
        - name: booklore
          image: ghcr.io/booklore-app/booklore:v2.2.1
          imagePullPolicy: Always
          env:
          - name: TZ
            value: "Europe/Helsinki"
          - name: USER_ID
            value: "1000"
          - name: GROUP_ID
            value: "1000"
          - name: BOOKLORE_PORT
            value: "6060"
          - name: DATABASE_URL
            value: "jdbc:mariadb://127.0.0.1:3306/booklore"
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: booklore-user-password
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: booklore-user-password
                key: password
          securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
              add:
                - SETUID
                - SETGID
                - CHOWN
                - DAC_OVERRIDE
                - NET_BIND_SERVICE
          ports:
          - name: booklore-port
            containerPort: 6060
            protocol: TCP
          volumeMounts:
          - name: booklore-data
            mountPath: /app/data
          - name: booklore-bookdrop-pvc
            mountPath: /bookdrop
          - name: books
            mountPath: /ebooks
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "2"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: mariadb-run
        emptyDir: {}
      - name: mariadb-config
        persistentVolumeClaim:
          claimName: "booklore-mariadb-pvc"
      - name: booklore-data
        persistentVolumeClaim:
          claimName: "booklore-data-pvc"
      - name: booklore-bookdrop-pvc
        persistentVolumeClaim:
          claimName: "booklore-bookdrop-pvc"
      - name: books
        persistentVolumeClaim:
          claimName: media-nfs-pvc
  selector:
    matchLabels:
      app: booklore