---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./cnpg/app/ks.yaml
  - ./cnpg/secrets/ks.yaml
  - ./cnpg/databases/ks.yaml
  - ./barman/certificates/ks.yaml
  - ./barman/barman/ks.yaml
  - ./barman/object-store/ks.yaml
