apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:52ok0qLUCCOAUdKqSNyxCkceTNpS3IGfNbLcLnIGZDayswUJTKoSWGF8ToHaPaQw1rx1RZs76/4uTrW5LO7nm4fzG3pVb0uDrDrpUNM=,iv:B7IJF46WPeaw1qvqAbLQLsbdP1lLOreU9gehsUkV+Ow=,tag:0gJAciHBrq7sv5BIJH7MdA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOV1l4dmhUMmtOMk9Yb0Vq
            dXlUblpMOE5oYUhTZk0yMzgvb0FGK2EzT2lVCmNMZ0JTcVE0MEdPRng1UHdXVFdj
            Z1Qxenk0aXNvTVg4dmZLZ29GNi9lZ1kKLS0tIGYyVVhlMXdTSGdUZllBc3R5Rnk0
            MXVVVmQzekpMRktTNFFRM1FkaGRyRW8KzmFfQUy1MYWFYpK4eXKVv5hVBsDx89Gz
            bhQ6jhdp8G01gAYG+ARuePrhoH7VF57FYEodprohRjXifDX44NAmYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mlu0sfujfyh3w0hm94azdz6d88yu0jmvdy8t5hs7j8q6jtwm2ejsch03hg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRVZ4WTJhNlVmMkpUMUNa
            QWEwM0pGOUdmVTEycnJDdzdNY2JKVUR0MlFFCmR1WVV2WHdZQ2ZFYittRkVKSzV2
            bHpzMzRUMnBGVGVYOW14bEhJZ0hjWk0KLS0tIHcyYkpjRjZkdUVZckdxRVpFenVK
            ZE5UUmJEbUNwMXFUNDZ1WisySlBYd1UKeftkm4B1aAIgb+1oibU7AiWRbcGhAJrZ
            p7gZ5jVpg5rfFr12mOeaqY+GVJf5qWB9OTMhNqy5FV15TdlNkkPM/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tcr89ezp74jk9xmfzmra3k26644w38xmep7azhxgy968285jrvvska5j8k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T14:47:58Z"
    mac: ENC[AES256_GCM,data:ivtjmR0CIyHE19QJBlW51mBR0KEO8cXCCOtyR76mwO9JbvGpQQbXM+i5EXblvnVRIJncUNA4xKSZkoNXX0cgpLM4ucWxn4yXT4C8q8ViRALlnkQXNsu1voIkwo0luQ4rcoLhYv2ZfqqbLFDGxre6zikPmwvOTnZqSm2RH2Jak/4=,iv:QTPaw+oZerCOvkX/HqJMUCKMg9AAzwowhw0ImADl/94=,tag:9qkpUlZYeE0sqGy38XHmVA==,type:str]
    version: 3.13.2
