apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:xM72G0ohHQLmYWXPANhSL5yzqc6duYU0/+frHvqXJgg0T+W9Gu9mHt1R57WKMOggH4TYvgqoD6vifQnffl8j1oqNQBI8rlPbrlqF7Aq1dXxgzFr5FZhgikbOc/mSQwXpTDSPi5i7HCbMsKNROYAuj3ssEyQDdvsj1oa7sWqupiM5q5POexhDGLlmUMWPdgy28UuxJU0inmwkr9CIloOLm9oAvaYp1CBJC5p3d9W+yhWFoeXdah61aJICbsZcM8ZcIt+uimqJc8mS8KQU+rbEj7eMJvU+LPmSsM7JiEYy3oPN4kZ2PKoek0pxm5NJh3BL5QxenMjB1+G+MMgiU74hKSinzjXUk1IiGdz0JQwZHksqB/3AwdcIpOdz5UbfznfGbE9H3I8etXuw9EbztkRAa0olDSSnzmAUW6YIwwGK/0MxYmV12zusshj4wOLHvV3FyDftBhy4l5kbmJgKl08qUCyIATpB4ywl3KYOdECsRwKFlEiTIplqPHSxzp2qxlH0FZZ/5pgUilqFTwsQyzPYd6RKfRkakNNh1ObQ6pwbvTG2aV1ivKga/sF1TsBchWwIGye3dpqJ8NlHZomYr3CYe5cbjUn07Gp99CLthLk4/LEBXDrl5mYqriydfKRqDGHnXFYOiCu+ppqDvfUHnLNSWyiR2r0oIsPntIHwEwYBCREGc1vAaKe6XQhf6XoFOXq5NSjO3RoPPD/H9I8pL5yYlFbujt/odCU3qkA7zBuq08vMlA2FIssk3NAPXXVpC0p4AgkT+FITnd0Vie3ecEa1R8D7lgEnSjAID9S4SiVwjyfDwKidj5l04xTBtuOD/9IqRfIrt6Y2uY0ipicEooCMpKBA,iv:N8cXaMaL2LD/2Uon7WlQsTMB/2I41DhOaxvYNZcgNtg=,tag:5ikrXw15c9PyyY6+zGe5kA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age190ldxpeqm783nz8rf3cxeajq2m0rflan4huhau8fz9tqcj96wgvsmycw9d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVUtWQkFlMmUrcHBvN1RC
            Y0l5cllocHlGdGdhN3JKbUhnSXpqV2ZQeUM4CjVnNnpNQW5JY3JhZjN4UmMzNVc3
            dWRidHZnMkszT3Y5RWw4eksyWlZSV2MKLS0tIDlkVlFNTUMxcjBkVFZWZDR6dlNK
            NThHVzVnZGhSMTZ1UDI2MmpSNkZ4OU0KRfG7kSrW81vY9nNwAgxlqRFqpb5P6LC3
            kE87gW4JPjUxrwjIqOh9vwH9T32s04vtoS4AzW/VsH41Dmn5HgDchw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T21:01:44Z"
    mac: ENC[AES256_GCM,data:VqRA3HK87RfMzY/Wcii7mf0tDACmuXDI/NmAjIHXlCxHvqS5iBEd7ba0/9YMANfQSpPPUVu01ee6gmOSmQ9RwHSwPnN21KdxCR5W3czy63jnWhiUUcTJnpajSQuBFX85ELnDG+aejYfyV34yXLXfBJ3nfEwqZ7FTpQSCSWPG7g4=,iv:QFHnGUkcq/FMDuphMc/cZ74PdZZQ7z00ZBzGrfS+fzM=,tag:KpFgvFwq0M/BMLh4xYEvHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
