apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app certificates
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/cluster0/kubernetes/apps/cert-manager/cert-manager/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 3m
  retryInterval: 1m
  timeout: 3m
  dependsOn:
    - name: ca-certificates
