apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: continuwuity-credentials
    namespace: matrix
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword-connect
    target:
        creationPolicy: Owner
    data:
        - secretKey: token
          remoteRef:
            key: continuwuity-credentials
            property: token
        - secretKey: CONDUWUIT_EMERGENCY_PASSWORD
          remoteRef:
            key: continuwuity-credentials
            property: CONDUWUIT_EMERGENCY_PASSWORD


