apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: continuwuity
  name: continuwuity
  namespace: matrix
spec:
  serviceName: continuwuity-service
  replicas: 4
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: continuwuity
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - control-01
      containers:
        - image: ghcr.io/continuwuity/continuwuity
          imagePullPolicy: Always
          name: continuwuity
          env:
          - name: TZ
            value: "Europe/Helsinki"
          - name: CONDUWUIT_PORT
            value: "8080"
          - name: CONDUWUIT_DATABASE_PATH
            value: "/data"
          - name: CONDUWUIT_DATABASE_BACKUP_PATH
            value: "/backup"
          - name: CONDUWUIT_DATABASE_BACKUPS_TO_KEEP
            value: "1"
          - name: CONDUWUIT_QUERY_TRUSTED_KEY_SERVERS_FIRST
            value: "false"
          - name: CONDUWUIT_QUERY_TRUSTED_KEY_SERVERS_FIRST_ON_JOIN
            value: "false"
          - name: CONDUWUIT_FORBIDDEN_REMOTE_SERVER_NAMES
            value: |
              ["matrix.org"]
          - name: CONDUWUIT_FORBIDDEN_REMOTE_ROOM_DIRECTORY_SERVER_NAMES
            value: |
              ["matrix.org"]
          - name: CONDUWUIT_URL_PREVIEW_DOMAIN_EXPLICIT_DENYLIST
            value: |
              ["matrix.org"]
          - name: CONTINUWUITY_SERVER_NAME
            value: "matrix.biggs.dog"
          - name: CONTINUWUITY_MAX_REQUEST_SIZE
            value: "28000000"
          - name: CONTINUWUITY_ALLOW_REGISTRATION
            value: "true"
          - name: CONTINUWUITY_REGISTRATION_TOKEN
            valueFrom:
              secretKeyRef:
                name: continuwuity-credentials
                key: token
          - name: CONDUWUIT_EMERGENCY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: continuwuity-credentials
                key: CONDUWUIT_EMERGENCY_PASSWORD
          - name: CONTINUWUITY_ALLOW_FEDERATION
            value: "true"
          - name: CONTINUWUITY_ALLOW_CHECK_FOR_UPDATES
            value: "false"
          - name: CONTINUWUITY_ADDRESS
            value: "0.0.0.0"
          - name: NEW_USER_DISPLAYNAME_SUFFIX
            value: ""
          - name: ALLOW_LEGACY_MEDIA
            value: "true"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: uwu-port
              containerPort: 8080
              protocol: TCP
          volumeMounts:
          - name: continuwuity-data
            mountPath: /data
          - name: continuwuity-backup
            mountPath: /backup
          resources:
            limits:
              memory: 3Gi
              cpu: "1.5"
            requests:
              memory: 3Gi
              cpu: "1.5"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  selector:
    matchLabels:
      app: continuwuity
  volumeClaimTemplates:
    - metadata:
        name: continuwuity-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: host-path
        resources:
          requests:
            storage: 100Gi
    - metadata:
        name: continuwuity-backup
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ceph-block
        resources:
          requests:
            storage: 100Gi
  
