apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: continuwuity
  name: continuwuity
  namespace: matrix
spec:
  serviceName: continuwuity-service
  replicas: 4
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: continuwuity
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      enableServiceLinks: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - control-01
      containers:
        - image: ghcr.io/continuwuity/continuwuity
          imagePullPolicy: Always
          name: continuwuity
          env:
          - name: CONTINUWUITY_PORT
            value: "8080"
          - name: CONTINUWUITY_DATABASE_PATH
            value: "/data"
          - name: CONTINUWUITY_DATABASE_BACKUP_PATH
            value: "/backup"
          - name: CONTINUWUITY_DATABASE_BACKUPS_TO_KEEP
            value: "1"
          - name: CONTINUWUITY_ROCKSDB_PARALLELISM_THREADS
            value: "4"
          - name: CONTINUWUITY_QUERY_TRUSTED_KEY_SERVERS_FIRST
            value: "false"
          - name: CONTINUWUITY_QUERY_TRUSTED_KEY_SERVERS_FIRST_ON_JOIN
            value: "false"
          - name: CONTINUWUITY_FORBIDDEN_REMOTE_SERVER_NAMES
            value: |
              ["matrix.org"]
          - name: CONTINUWUITY_FORBIDDEN_REMOTE_ROOM_DIRECTORY_SERVER_NAMES
            value: |
              ["matrix.org"]
          - name: CONTINUWUITY_URL_PREVIEW_DOMAIN_EXPLICIT_DENYLIST
            value: |
              ["matrix.org"]
          - name: CONTINUWUITY_SERVER_NAME
            value: "biggs.dog"
          - name: CONTINUWUITY_WELL_KNOWN_CLIENT
            value: "https://matrix.biggs.dog"
          - name: CONTINUWUITY_WELL_KNOWN_SERVER
            value: "matrix.biggs.dog:443"
          - name: CONTINUWUITY_MAX_REQUEST_SIZE
            value: "28000000"
          - name: CONTINUWUITY_ALLOW_REGISTRATION
            value: "true"
          - name: CONTINUWUITY_REGISTRATION_TOKEN
            valueFrom:
              secretKeyRef:
                name: continuwuity-credentials
                key: token
          # - name: CONTINUWUITY_EMERGENCY_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: continuwuity-credentials
          #       key: CONTINUWUITY_EMERGENCY_PASSWORD
          - name: CONTINUWUITY_ALLOW_FEDERATION
            value: "true"
          - name: CONTINUWUITY_ALLOW_CHECK_FOR_UPDATES
            value: "false"
          - name: CONTINUWUITY_ADDRESS
            value: "0.0.0.0"
          - name: NEW_USER_DISPLAYNAME_SUFFIX
            value: ""
          - name: ALLOW_LEGACY_MEDIA
            value: "true"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: uwu-port
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
          - name: continuwuity-data
            mountPath: /data
          - name: continuwuity-backup
            mountPath: /backup
          resources:
            limits:
              memory: 3Gi
              cpu: "1.5"
            requests:
              memory: 3Gi
              cpu: "1.5"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  selector:
    matchLabels:
      app: continuwuity
  volumeClaimTemplates:
    - metadata:
        name: continuwuity-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: host-path
        resources:
          requests:
            storage: 100Gi
    - metadata:
        name: continuwuity-backup
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ceph-block
        resources:
          requests:
            storage: 100Gi
  
