apiVersion: v1
kind: Service
metadata:
  name: continuwuity-service
  namespace: matrix
spec:
  selector:
    app: continuwuity
  ports:
    - name: continuwuity-port
      port: 6167
      protocol: TCP
      targetPort: 6167
    - name: continuwuity-federation-port
      port: 80
      protocol: TCP
      targetPort: 80