---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: continuwuity
  namespace: observability
spec:
  hostnames:
  - matrix.biggs.dog
  parentRefs:
  - name: wildcard-biggs-dog
    namespace: networking
  rules:
  - backendRefs:
    - name: continuwuity
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /