apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: matrix-baseline-policy
  namespace: matrix
spec:
  endpointSelector: {}
  egress:
    # 1. DNS
    - toEndpoints:
        - matchLabels:
            "io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    # 2. K8s API
    - toEntities:
        - kube-apiserver
