apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netbird
  namespace: netbird
  labels:
    app.kubernetes.io/name: netbird
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - netbird.biggs.dog
      secretName: netbird-biggs-dog-tls
  rules:
    - host: netbird.biggs.dog
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: netbird-server
                port:
                  name: mgmt
          - path: /ws-proxy
            pathType: Prefix
            backend:
              service:
                name: netbird-server
                port:
                  name: signal
          - path: /relay
            pathType: Prefix
            backend:
              service:
                name: netbird-server
                port:
                  name: relay
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: netbird-server
                port:
                  name: mgmt
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netbird-dashboard
                port:
                  name: http
